#!/bin/zsh
#generate the figures.  Pause to allow user to change the selected layers for each figure.
diagram_file="model.drawio"
ext=".png"
prompt="Change the file to select layers for "
fn="figures.txt"
while read line
do
  echo $prompt$line
  read whatever </dev/tty
  /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o $line$ext $diagram_file
done < $fn