#!/bin/zsh
#generate the figures.  Pause to allow user to change the selected layers for each figure.
diagram_file="model.drawio"
folder="resources/"
ext=".png"
prompt="Change the file to select layers for "
fn="figures.txt"
while read line
do
  echo $prompt$line
  read whatever </dev/tty
  ofile=`echo $line | cut -f 1 -d " "` 
  /Applications/draw.io.app/Contents/MacOS/draw.io -x -f png -o $folder$ofile$ext $diagram_file
done < $fn